[package]
name = "multihook"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.1"
thiserror = "1.0.26"

[dependencies.tokio]
version = "1.9.0"
features = ["macros", "rt-multi-thread", "process"]